-- D:\225TMDT\TMDT-Website\database\01-create-tables.sql

USE master;
GO

IF DB_ID('ZenTekExchange') IS NOT NULL
BEGIN
    ALTER DATABASE ZenTekExchange SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE ZenTekExchange;
END
GO

CREATE DATABASE ZenTekExchange;
GO

USE ZenTekExchange;
GO

-- 3. Create tables

CREATE TABLE VaiTro (
    MaVaiTro UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenVaiTro NVARCHAR(50) UNIQUE NOT NULL,
    MoTa NVARCHAR(255) NULL
);

CREATE TABLE NguoiDung (
    MaNguoiDung UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenDangNhap VARCHAR(12) UNIQUE NOT NULL,
    MatKhauHash VARCHAR(255) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai CHAR(10) NULL,
    VaiTroId UNIQUEIDENTIFIER NOT NULL,
    AnhDaiDien VARCHAR(MAX) NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL
);

CREATE TABLE CuaHang (
    MaCuaHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NguoiBanId UNIQUEIDENTIFIER UNIQUE NOT NULL,
    TenCuaHang NVARCHAR(50) NOT NULL,
    MoTa NVARCHAR(500) NULL,
    Logo VARCHAR(255) NULL,
    DiaChi NVARCHAR(300) NOT NULL,
    PhuongXa NVARCHAR(100) NOT NULL,
    QuanHuyen NVARCHAR(100) NOT NULL,
    TinhThanh NVARCHAR(100) NOT NULL,
    SoDienThoai CHAR(10) NOT NULL,
    LoaiHinhCuaHang TINYINT NOT NULL DEFAULT 1,
    MaSoThue NVARCHAR(20) NULL,
    PdfGiayPhep VARCHAR(255) NULL,
    DaXacThucPhapLy BIT NOT NULL DEFAULT 0,
    LyDoTuChoi NVARCHAR(500) NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    TrangThai BIT NOT NULL DEFAULT 1
);

CREATE TABLE DanhMuc (
    MaDanhMuc UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenDanhMuc NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(MAX) NULL,
    DanhMucChaId UNIQUEIDENTIFIER NULL,
    Icon VARCHAR(MAX) NOT NULL,
    ThuTuHienThi INT NOT NULL DEFAULT 1,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE SanPham (
    MaSanPham UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CuaHangId UNIQUEIDENTIFIER NOT NULL,
    DanhMucId UNIQUEIDENTIFIER NOT NULL,
    TieuDe NVARCHAR(200) NOT NULL,
    FileMoTa NVARCHAR(MAX) NULL,
    Gia DECIMAL(12,2) NOT NULL,
    TinhTrang NVARCHAR(10) NOT NULL,
    SoLuong INT NOT NULL DEFAULT 1,
    SoLuongDaBan INT NOT NULL DEFAULT 0,
    LuotXem INT NOT NULL DEFAULT 0,
    DiemDanhGia DECIMAL(1,1) NOT NULL DEFAULT 0.0,
    LinkSanPham VARCHAR(500) NULL,
    SoLuongGioHang INT NOT NULL DEFAULT 0,
    TrangThaiDuyet NVARCHAR(20) NOT NULL DEFAULT N'Chờ phê duyệt',
    NguoiDuyetId UNIQUEIDENTIFIER NULL,
    NgayDuyet DATETIME NULL,
    TrangThaiHienThi BIT NOT NULL DEFAULT 1,
    NgayDang DATETIME NOT NULL DEFAULT GETDATE(),
    NgaySua DATETIME NULL,
    DaHetHang BIT NOT NULL DEFAULT 0
);

CREATE TABLE AnhSanPham (
    MaHinhAnh UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SanPhamId UNIQUEIDENTIFIER NOT NULL,
    DuongDanAnh VARCHAR(500) NOT NULL,
    LaAnhChinh BIT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE PhanLoai (
    MaPhanLoai UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenPhanLoai NVARCHAR(100) NOT NULL,
    SanPhamId UNIQUEIDENTIFIER NOT NULL,
    HinhAnhId UNIQUEIDENTIFIER NOT NULL
);

CREATE TABLE GioHang (
    MaGioHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NguoiMuaId UNIQUEIDENTIFIER UNIQUE NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ChiTietGioHang (
    MaChiTietGioHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    GioHangId UNIQUEIDENTIFIER NOT NULL,
    SanPhamId UNIQUEIDENTIFIER NOT NULL,
    PhanLoaiId UNIQUEIDENTIFIER NOT NULL,
    SoLuong INT NOT NULL DEFAULT 1,
    DonGia DECIMAL(12,2) NOT NULL
);

CREATE TABLE DonHang (
    MaDonHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    NguoiMuaId UNIQUEIDENTIFIER NOT NULL,
    HoTenNguoiNhan NVARCHAR(100) NOT NULL,
    SoDienThoaiNguoiNhan CHAR(10) NOT NULL,
    DiaChiNhan NVARCHAR(255) NOT NULL,
    TrangThaiDon NVARCHAR(20) NOT NULL DEFAULT N'Chờ xử lý',
    LyDoHuy NVARCHAR(500) NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ChiTietDonHang (
    MaChiTietDonHang UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    DonHangId UNIQUEIDENTIFIER NOT NULL,
    SanPhamId UNIQUEIDENTIFIER NOT NULL,
    PhanLoaiId UNIQUEIDENTIFIER NULL,
    SoLuong INT NOT NULL DEFAULT 1,
    DonGia DECIMAL(12,2) NOT NULL,
    GhiChu NVARCHAR(255) NULL
);

CREATE TABLE DanhGiaSanPham (
    MaDanhGia UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    SanPhamId UNIQUEIDENTIFIER NOT NULL,
    NguoiMuaId UNIQUEIDENTIFIER NOT NULL,
    DonHangId UNIQUEIDENTIFIER NOT NULL,
    SoSao TINYINT NOT NULL,
    NoiDung NVARCHAR(MAX) NULL,
    DuongDanVideo VARCHAR(500) NULL,
    HuuIch INT NOT NULL DEFAULT 0,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NULL,
    TraLoiNoiDung NVARCHAR(MAX) NULL,
    TraLoiNgayTao DATETIME NULL,
    TraLoiNgayCapNhat DATETIME NULL
);

CREATE TABLE PhanHoiMedia (
    MaPhanHoi UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    DanhGiaId UNIQUEIDENTIFIER NULL,
    TinNhanId UNIQUEIDENTIFIER NULL,
    LoaiPhanHoi NVARCHAR(20) NOT NULL,
    LoaiMedia NVARCHAR(10) NOT NULL,
    DuongDanMedia VARCHAR(500) NOT NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE CuocTroChuyen (
    MaCuocTroChuyen UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenCuocTroChuyen NVARCHAR(255) NULL,
    Loai NVARCHAR(20) NOT NULL DEFAULT 'ca_nhan',
    TinNhanCuoiId UNIQUEIDENTIFIER NULL,
    NgayTao DATETIME NOT NULL DEFAULT GETDATE(),
    NgayCapNhat DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE ThanhVienCuocTroChuyen (
    MaThanhVien UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CuocTroChuyenId UNIQUEIDENTIFIER NOT NULL,
    NguoiDungId UNIQUEIDENTIFIER NOT NULL,
    VaiTro NVARCHAR(20) NOT NULL DEFAULT 'thanh_vien',
    NgayThamGia DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT UQ_ThanhVienCuocTroChuyen UNIQUE (CuocTroChuyenId, NguoiDungId)
);

CREATE TABLE TinNhan (
    MaTinNhan UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CuocTroChuyenId UNIQUEIDENTIFIER NOT NULL,
    NguoiGuiId UNIQUEIDENTIFIER NOT NULL,
    NoiDung NVARCHAR(MAX) NULL,
    DaDoc BIT NOT NULL DEFAULT 0,
    NgayGui DATETIME NOT NULL DEFAULT GETDATE()
);
